### PR TITLE
Fix WS-2018-0594 potential non-random UUIDs security issue

### PR DESCRIPTION
**Pull request by xumia**
A vulnerability was found in github.com/satori/go.uuid through version v1.2.0. The UUID random generator uses Read() function which has fewer bytes than asked and might cause potential non-random UUIDs.

See advisory for vulnerability details
From CERT: https://github.com/satori/go.uuid/pull/75/commits/75cca531ea763666bc46e531da3b4c3b95f64557

More detail alert info can be found on https://msazure.visualstudio.com/One/_componentGovernance/Networking-acs-buildimage/alert/4546641?typeId=5886163

Fix multiple-value uuid.NewV4() in single-value context issue.

### CODE REVIEW

**Comment by xumia** [comment]
More detail alert info can be found on https://msazure.visualstudio.com/One/_componentGovernance/Networking-acs-buildimage/alert/4546641?typeId=5886163

**Comment by qiluo-msft** [comment]
lgtm. @sumukhatv could you help review?

**Comment by sumukhatv** [comment]
@xumia Did test/apitest.py pass with this change?

**Comment by xumia** [comment]
Test results:
test_vnet_name_mapping_logic (__main__.ra_client_positive_tests) ... ok

----------------------------------------------------------------------
Ran 32 tests in 35.470s

OK

test_vrouter_not_created_all_verbs (__main__.ra_client_negative_tests) ... ok

----------------------------------------------------------------------
Ran 23 tests in 24.653s

OK

**Comment by xumia** [comment]
@sumukhatv , thanks for your comment, there is an API change, fixed.

**Comment by xumia** [comment]
@sumukhatv , the test is based on the change: https://github.com/Azure/sonic-restapi/pull/81

**Comment by sumukhatv** [comment]
> @sumukhatv , the test is based on the change: #81

Does it mean that we need to merge #81 for the tests to pass for this PR?

**Comment by xumia** [comment]
@sumukhatv , this PR does not have any dependencies on the PR, the PR is a general fix. The test steps do not work following the readme. It should be another issue.

**Review by sumukhatv — APPROVED** [review]

**Comment by sumukhatv** [comment]
@prsunny for visibility

**Comment by sumukhatv** [comment]
All the tests are passing. Good to merge:

~/sonic-restapi/test$ python apitest.py 
test_config_status_reset_get (__main__.ra_client_positive_tests) ... ok
test_config_status_reset_post (__main__.ra_client_positive_tests) ... ok
test_delete_config_tunnel_decap_tunnel_type (__main__.ra_client_positive_tests) ... ok
test_delete_encap (__main__.ra_client_positive_tests) ... ok
test_delete_vrouter (__main__.ra_client_positive_tests) ... ok
test_duplicate_vni (__main__.ra_client_positive_tests) ... ok
test_get_all_vlans (__main__.ra_client_positive_tests) ... ok
test_get_encap (__main__.ra_client_positive_tests) ... ok
test_get_members_per_vlan (__main__.ra_client_positive_tests) ... ok
test_get_neighbors_per_vlan (__main__.ra_client_positive_tests) ... ok
test_get_vlans_per_vnetid_1digitvlans (__main__.ra_client_positive_tests) ... ok
test_get_vlans_per_vnetid_4digitvlans (__main__.ra_client_positive_tests) ... ok
test_get_vrouter (__main__.ra_client_positive_tests) ... ok
test_guid_persistence (__main__.ra_client_positive_tests) ... ok
test_local_subnet_route_addition (__main__.ra_client_positive_tests) ... ok
test_patch_routes_drop_bm_routes_local (__main__.ra_client_positive_tests) ... ok
test_patch_routes_drop_bm_routes_tunnel (__main__.ra_client_positive_tests) ... ok
test_patch_update_routes_with_optional_args (__main__.ra_client_positive_tests) ... ok
test_post_config_tunnel_decap_tunnel_type (__main__.ra_client_positive_tests) ... ok
test_post_encap (__main__.ra_client_positive_tests) ... ok
test_post_ping (__main__.ra_client_positive_tests) ... ok
test_post_vrouter (__main__.ra_client_positive_tests) ... ok
test_routes_all_verbs (__main__.ra_client_positive_tests) ... ok
test_vlan_all_args_all_verbs (__main__.ra_client_positive_tests) ... ok
test_vlan_member_notagging_all_verbs (__main__.ra_client_positive_tests) ... ok
test_vlan_member_tagged_untagged_interop (__main__.ra_client_positive_tests) ... ok
test_vlan_member_tagging_all_verbs (__main__.ra_client_positive_tests) ... ok
test_vlan_neighbor_all_verbs (__main__.ra_client_positive_tests) ... ok
test_vlan_with_ippref_all_verbs (__main__.ra_client_positive_tests) ... ok
test_vlan_with_vnetid_all_verbs (__main__.ra_client_positive_tests) ... ok
test_vlan_wo_ippref_vnetid_all_verbs (__main__.ra_client_positive_tests) ... ok
test_vnet_name_mapping_logic (__main__.ra_client_positive_tests) ... ok

----------------------------------------------------------------------
Ran 32 tests in 35.560s

OK
test_delete_config_tunnel_decap_tunnel_type_not_vxlan (__main__.ra_client_negative_tests) ... ok
test_delete_vlan_member_not_created (__main__.ra_client_negative_tests) ... ok
test_delete_vlan_neighbor_not_created (__main__.ra_client_negative_tests) ... ok
test_delete_vlan_with_dependencies (__main__.ra_client_negative_tests) ... ok
test_delete_vrouter_with_dependencies (__main__.ra_client_negative_tests) ... ok
test_get_config_tunnel_decap_tunnel_not_created (__main__.ra_client_negative_tests) ... ok
test_get_vlan_member_not_created (__main__.ra_client_negative_tests) ... ok
test_get_vlan_neighbor_not_created (__main__.ra_client_negative_tests) ... ok
test_get_vlans_per_vnetid_invalid_vlan (__main__.ra_client_negative_tests) ... ok
test_get_vlans_per_vnetid_invalid_vnet (__main__.ra_client_negative_tests) ... ok
test_patch_delete_routes_not_created (__main__.ra_client_negative_tests) ... ok
test_post_ping_invalid (__main__.ra_client_negative_tests) ... ok
test_post_vlan_mem_which_exists_tagged (__main__.ra_client_negative_tests) ... ok
test_post_vlan_mem_which_exists_untagged (__main__.ra_client_negative_tests) ... ok
test_post_vlan_neighbor_which_exists (__main__.ra_client_negative_tests) ... ok
test_post_vlan_which_exists (__main__.ra_client_negative_tests) ... ok
test_post_vrouter_malformed_arg (__main__.ra_client_negative_tests) ... ok
test_post_vrouter_which_exists (__main__.ra_client_negative_tests) ... ok
test_post_vrouter_without_vtep (__main__.ra_client_negative_tests) ... ok
test_vlan_neighbor_not_valid_ip (__main__.ra_client_negative_tests) ... ok
test_vlan_not_created_all_verbs (__main__.ra_client_negative_tests) ... ok
test_vlan_out_of_range (__main__.ra_client_negative_tests) ... ok
test_vrouter_not_created_all_verbs (__main__.ra_client_negative_tests) ... ok

----------------------------------------------------------------------
Ran 23 tests in 24.663s

OK

**Pull request merged**
